### PR TITLE
Uploads

### PR DESCRIPTION
**Pull request by justinmc**
This is the frontend that will consume the upload endpoint.  Branched off of and waiting on: https://github.com/Autodesk/molecular-design-applications/pull/12

### CODE REVIEW

**Comment by justinmc** [comment]
Here's what it looks like right now, using the live backend api:

upload_with_backend

**Comment by justinmc** [comment]
@dionjwa Can you review this?  Take a look at the gif above (or try it out for yourself) and let me know what you think for this iteration.  What else needs to happen in this sprint?  Notice the ugly spinner on the left, which never finishes because we no longer have a gallery api.  Is that something we should handle now?

**Comment by dionjwa** [comment]
Yeah, we don't have the gallery right now, so that should be disabled for the moment.

**Comment by dionjwa** [comment]
` npm install && npm run build` results in: 
```
Condition always false [./~/style-loader!./~/css-loader!./~/sass-loader!./public/css/workflow.scss:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/sass-loader!./public/css/workflow.scss:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/sass-loader!./public/css/workflow.scss:7,0]

ERROR in ./public/js/main.jsx

/Users/dionamago/autodesk/mdt-cloud-workflow-prototype/client/public/js/main.jsx
  13:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../index.html'            import/no-unresolved
  17:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../404.html'              import/no-unresolved
  18:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../browserconfig.xml'     import/no-unresolved
  19:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../favicon.ico'           import/no-unresolved
  20:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../humans.txt'            import/no-unresolved
  21:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../LICENSE.txt'           import/no-unresolved
  22:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../robots.txt'            import/no-unresolved
  23:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../apple-touch-icon.png'  import/no-unresolved
  24:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../tile.png'              import/no-unresolved
  25:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../crossdomain.xml'       import/no-unresolved
  26:9  error  Unable to resolve path to module 'file?name=[name].[ext]!../tile-wide.png'         import/no-unresolved

✖ 11 problems (11 errors, 0 warnings)


ERROR in ./public/js/components/view.jsx

/Users/dionamago/autodesk/mdt-cloud-workflow-prototype/client/public/js/components/view.jsx
  4:28  error  Unable to resolve path to module 'molecule-3d-for-react'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)


ERROR in ./public/js/components/view.jsx
Module not found: Error: Cannot resolve module 'molecule-3d-for-react' in /Users/dionamago/autodesk/mdt-cloud-workflow-prototype/client/public/js/components
 @ ./public/js/components/view.jsx 15:26-58

```

**Comment by justinmc** [comment]
Fixed the above install problems in the last few commits and confirmed with Dion.  Merging!

**Pull request merged**
