### PR TITLE
Safari Height Bug

### PR DESCRIPTION
**Pull request by justinmc**
Big white area at the bottom before:

screen shot 2017-02-21 at 10 00 37 am

Full height after:
screen shot 2017-02-21 at 10 00 59 am

### CODE REVIEW

**Comment by avirshup** [comment]
@justinmc - I'm still getting an issue with the viewer in my Safari:
image

This is Safari 9.1.1 (11601.6.17)

Am getting one error in the Safari console:
```[Error] SyntaxError: JSON Parse error: Unrecognized token '<'
	parse
	onload```
![image](https://cloud.githubusercontent.com/assets/9388007/23277192/db426f88-f9c1-11e6-9fa6-46b142cc140d.png)

**Comment by justinmc** [comment]
@avirshup I think I got it now, let me know.  Thank you for trying this on your machine by the way, otherwise we wouldn't have caught that!

**Comment by avirshup** [comment]
@justinmc - the page looks great - and now I'm seeing something weird in the waiting/status page:

image

**Comment by avirshup** [comment]
Also realized that the workflow title is getting cut off:
image

**Comment by justinmc** [comment]
@avirshup I think I fixed those, but let me know if you still see the cutoff title, because I couldn't quite reproduce it like in your screenshot.

**Comment by avirshup** [comment]
Looks great! :+1: to merge

**Pull request merged**
