### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by justinmc**
This PR will add Travis CI support to the repository!

### CODE REVIEW

**Comment by justinmc** [comment]
@PeterRJones Any way to get the tirrenu tarball into Travis in a nice way?  Or we can always wait until we've got a way to deploy that publicly.  See: https://travis-ci.org/Autodesk/molecular-design-applications

**Comment by dionjwa** [comment]
@justinmc Does this PR include building the docker image?

**Comment by justinmc** [comment]
@dionjwa No not yet. Travis would clone, `npm install`, and run the tests (client unit tests only) without using Docker for now.  I think this is a valuable stepping stone without it, unless you know how to get that working quickly.

**Comment by PeterRJones** [comment]
@justinmc best to wait until viewer can be accessed publicly.

**Comment by justinmc** [comment]
@PeterRJones Got it, I'll put this on hold until then.

**Pull request closed without merging**
